[package]
name = "helpers"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pass-fxa-lib = { path = "../lib" }
tokio = { version = "1.13.1", features = ["full"] }
serde_json = "1.0.66"
